// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Tilt_Tester

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void KeyboardDone(lv_event_t * e);
void ZeroButton(lv_event_t * e);
void MoveToAngleButton(lv_event_t * e);
void MoveByAngleButton(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
