// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Tilt_Tester

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TopPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_TopPanel, 180);
    lv_obj_set_height(ui_TopPanel, 50);
    lv_obj_set_x(ui_TopPanel, 0);
    lv_obj_set_y(ui_TopPanel, -5);
    lv_obj_set_align(ui_TopPanel, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_TopPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TopLabel = lv_label_create(ui_TopPanel);
    lv_obj_set_width(ui_TopLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TopLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TopLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TopLabel, "SRG DMF Tilt Tester");
    lv_obj_set_style_text_color(ui_TopLabel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TopLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_BottomPanel, 320);
    lv_obj_set_height(ui_BottomPanel, 68);
    lv_obj_set_align(ui_BottomPanel, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_BottomPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BottomPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_BottomPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BottomPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BottomPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BottomPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BottomPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_BottomPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_BottomPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ZeroButton = lv_btn_create(ui_BottomPanel);
    lv_obj_set_width(ui_ZeroButton, 90);
    lv_obj_set_height(ui_ZeroButton, 50);
    lv_obj_set_align(ui_ZeroButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ZeroButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ZeroButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ZeroButton, lv_color_hex(0x282B30), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ZeroButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ZeroButton, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ZeroButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ZeroButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(ui_ZeroButton, ui_event_ZeroButton, LV_EVENT_ALL, NULL);

    ui_ZeroStepperLabel = lv_label_create(ui_ZeroButton);
    lv_obj_set_width(ui_ZeroStepperLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ZeroStepperLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ZeroStepperLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ZeroStepperLabel, "Zero Tester");
    lv_obj_set_style_text_color(ui_ZeroStepperLabel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ZeroStepperLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MoveToAngleButton = lv_btn_create(ui_BottomPanel);
    lv_obj_set_width(ui_MoveToAngleButton, 110);
    lv_obj_set_height(ui_MoveToAngleButton, 50);
    lv_obj_set_align(ui_MoveToAngleButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MoveToAngleButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MoveToAngleButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MoveToAngleButton, lv_color_hex(0x282B30), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MoveToAngleButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(ui_MoveToAngleButton, ui_event_MoveToAngleButton, LV_EVENT_ALL, NULL);

    ui_MoveToAngleLabel = lv_label_create(ui_MoveToAngleButton);
    lv_obj_set_width(ui_MoveToAngleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MoveToAngleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MoveToAngleLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MoveToAngleLabel, "Move to Angle");
    lv_obj_set_style_text_color(ui_MoveToAngleLabel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MoveToAngleLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MoveByAngleButton = lv_btn_create(ui_BottomPanel);
    lv_obj_set_width(ui_MoveByAngleButton, 110);
    lv_obj_set_height(ui_MoveByAngleButton, 50);
    lv_obj_set_align(ui_MoveByAngleButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MoveByAngleButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MoveByAngleButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MoveByAngleButton, lv_color_hex(0x282B30), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MoveByAngleButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(ui_MoveByAngleButton, ui_event_MoveByAngleButton, LV_EVENT_ALL, NULL);

    ui_MoveByLabel = lv_label_create(ui_MoveByAngleButton);
    lv_obj_set_width(ui_MoveByLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MoveByLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MoveByLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MoveByLabel, "Move By Angle");
    lv_obj_set_style_text_color(ui_MoveByLabel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MoveByLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    int labelWidth = 80;
    int textWidth = 130;
    int height = 40;
    ui_InputValuePanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_InputValuePanel, 230);
    lv_obj_set_height(ui_InputValuePanel, 135);
    lv_obj_set_x(ui_InputValuePanel, 0);
    lv_obj_set_y(ui_InputValuePanel, -5);
    //lv_obj_clear_flag(ui_InputValuePanel, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_scrollbar_mode(ui_InputValuePanel, LV_SCROLLBAR_MODE_AUTO);
    lv_obj_add_flag(ui_InputValuePanel, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_clear_flag(ui_InputValuePanel, LV_OBJ_FLAG_SCROLL_CHAIN);
    lv_obj_clear_flag(ui_InputValuePanel, LV_OBJ_FLAG_GESTURE_BUBBLE);
    lv_obj_set_align(ui_InputValuePanel, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_InputValuePanel, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_InputValuePanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_pad_all(ui_InputValuePanel, 1, LV_PART_MAIN);

    ui_MoveToAngleLabel1 = lv_label_create(ui_InputValuePanel);
    lv_obj_set_width(ui_MoveToAngleLabel1, labelWidth  );   /// 1
    lv_obj_set_height(ui_MoveToAngleLabel1, height);    /// 1
    lv_obj_set_align(ui_MoveToAngleLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MoveToAngleLabel1, "Move to Angle");
    lv_obj_set_style_text_color(ui_MoveToAngleLabel1, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MoveToAngleLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MoveToAngleLabel1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MoveToAngleTextArea = lv_textarea_create(ui_InputValuePanel);
    lv_obj_set_width(ui_MoveToAngleTextArea, textWidth );
    lv_obj_set_height(ui_MoveToAngleTextArea, height);
    lv_obj_set_align(ui_MoveToAngleTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_MoveToAngleTextArea, "Placeholder...");
    lv_obj_set_style_text_color(ui_MoveToAngleTextArea, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MoveToAngleTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_MoveByAngleLabel = lv_label_create(ui_InputValuePanel);
    lv_obj_set_width(ui_MoveByAngleLabel, labelWidth);   /// 1
    lv_obj_set_height(ui_MoveByAngleLabel, height);    /// 1
    lv_obj_set_align(ui_MoveByAngleLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MoveByAngleLabel, "Move by Angle");
    lv_obj_set_style_text_color(ui_MoveByAngleLabel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MoveByAngleLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MoveByAngleLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MoveByAngleTextArea = lv_textarea_create(ui_InputValuePanel);
    lv_obj_set_width(ui_MoveByAngleTextArea, textWidth);
    lv_obj_set_height(ui_MoveByAngleTextArea, height);
    lv_obj_set_align(ui_MoveByAngleTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_MoveByAngleTextArea, "Placeholder...");
    lv_obj_set_style_text_color(ui_MoveByAngleTextArea, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MoveByAngleTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_VelocityLabel = lv_label_create(ui_InputValuePanel);
    lv_obj_set_width(ui_VelocityLabel, labelWidth);   /// 1
    lv_obj_set_height(ui_VelocityLabel, height);    /// 1
    lv_obj_set_align(ui_VelocityLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VelocityLabel, "Motor Vel (Deg/s)");
    lv_obj_set_style_text_color(ui_VelocityLabel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VelocityLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VelocityLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VelocityTextArea = lv_textarea_create(ui_InputValuePanel);
    lv_obj_set_width(ui_VelocityTextArea, textWidth);
    lv_obj_set_height(ui_VelocityTextArea, height);
    lv_obj_set_align(ui_VelocityTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_VelocityTextArea, "Placeholder...");
    lv_obj_set_style_text_color(ui_VelocityTextArea, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VelocityTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_MotorAnglePanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_MotorAnglePanel, 85);
    lv_obj_set_height(ui_MotorAnglePanel, 135);
    lv_obj_set_x(ui_MotorAnglePanel, 0);
    lv_obj_set_y(ui_MotorAnglePanel, -5);
    lv_obj_set_align(ui_MotorAnglePanel, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_MotorAnglePanel, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_MotorAnglePanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MotorAnglePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Arc1 = lv_arc_create(ui_MotorAnglePanel);
    lv_obj_set_width(ui_Arc1, 70);
    lv_obj_set_height(ui_Arc1, 70);
    lv_obj_set_x(ui_Arc1, 101);
    lv_obj_set_y(ui_Arc1, -11);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Arc1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_range(ui_Arc1, 0, 180);
    lv_arc_set_value(ui_Arc1, 0);
    lv_obj_remove_style(ui_Arc1, NULL, LV_PART_KNOB);


    ui_Label6 = lv_label_create(ui_MotorAnglePanel);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "NA");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_Screen1);
    lv_keyboard_set_mode(ui_Keyboard1, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard1, 300);
    lv_obj_set_height(ui_Keyboard1, 120);
    lv_obj_set_x(ui_Keyboard1, 0);
    lv_obj_set_y(ui_Keyboard1, 60);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_MoveToAngleTextArea, ui_event_MoveToAngleTextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MoveByAngleTextArea, ui_event_MoveByAngleTextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_VelocityTextArea, ui_event_VelocityTextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);

}